"""Add core models for users and quran

Revision ID: 788fd14ef598
Revises: 
Create Date: 2026-01-21 22:23:55.355065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788fd14ef598'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quran_surahs',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_simple', sa.String(), nullable=True),
    sa.Column('name_arabic', sa.String(), nullable=True),
    sa.Column('revelation_place', sa.String(), nullable=True),
    sa.Column('revelation_order', sa.Integer(), nullable=True),
    sa.Column('verses_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_quran_surahs_name_simple'), 'quran_surahs', ['name_simple'], unique=False)
    op.create_index(op.f('ix_quran_surahs_number'), 'quran_surahs', ['number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('quran_verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=True),
    sa.Column('verse_number', sa.Integer(), nullable=True),
    sa.Column('verse_key', sa.String(), nullable=True),
    sa.Column('text_uthmani', sa.Text(), nullable=True),
    sa.Column('text_indopak', sa.Text(), nullable=True),
    sa.Column('juz_number', sa.Integer(), nullable=True),
    sa.Column('hizb_number', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sajdah_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['surah_number'], ['quran_surahs.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_verses_id'), 'quran_verses', ['id'], unique=False)
    op.create_index(op.f('ix_quran_verses_surah_number'), 'quran_verses', ['surah_number'], unique=False)
    op.create_index(op.f('ix_quran_verses_verse_key'), 'quran_verses', ['verse_key'], unique=False)
    op.create_index(op.f('ix_quran_verses_verse_number'), 'quran_verses', ['verse_number'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('verses_read_count', sa.Integer(), nullable=True),
    sa.Column('hasanat_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_sessions_id'), 'reading_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_reading_sessions_user_id'), 'reading_sessions', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_table('user_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_locations_id'), 'user_locations', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('privacy_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_verses_read', sa.Integer(), nullable=True),
    sa.Column('total_hasanat', sa.Integer(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_stats_id'), 'user_stats', ['id'], unique=False)
    op.create_table('quran_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('translator_name', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['quran_verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_translations_id'), 'quran_translations', ['id'], unique=False)
    op.create_index(op.f('ix_quran_translations_language_code'), 'quran_translations', ['language_code'], unique=False)
    op.create_index(op.f('ix_quran_translations_verse_id'), 'quran_translations', ['verse_id'], unique=False)
    op.create_table('verse_read_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('verse_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['quran_verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verse_read_history_id'), 'verse_read_history', ['id'], unique=False)
    op.create_index(op.f('ix_verse_read_history_user_id'), 'verse_read_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_verse_read_history_verse_id'), 'verse_read_history', ['verse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verse_read_history_verse_id'), table_name='verse_read_history')
    op.drop_index(op.f('ix_verse_read_history_user_id'), table_name='verse_read_history')
    op.drop_index(op.f('ix_verse_read_history_id'), table_name='verse_read_history')
    op.drop_table('verse_read_history')
    op.drop_index(op.f('ix_quran_translations_verse_id'), table_name='quran_translations')
    op.drop_index(op.f('ix_quran_translations_language_code'), table_name='quran_translations')
    op.drop_index(op.f('ix_quran_translations_id'), table_name='quran_translations')
    op.drop_table('quran_translations')
    op.drop_index(op.f('ix_user_stats_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_locations_id'), table_name='user_locations')
    op.drop_table('user_locations')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_reading_sessions_user_id'), table_name='reading_sessions')
    op.drop_index(op.f('ix_reading_sessions_id'), table_name='reading_sessions')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_quran_verses_verse_number'), table_name='quran_verses')
    op.drop_index(op.f('ix_quran_verses_verse_key'), table_name='quran_verses')
    op.drop_index(op.f('ix_quran_verses_surah_number'), table_name='quran_verses')
    op.drop_index(op.f('ix_quran_verses_id'), table_name='quran_verses')
    op.drop_table('quran_verses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quran_surahs_number'), table_name='quran_surahs')
    op.drop_index(op.f('ix_quran_surahs_name_simple'), table_name='quran_surahs')
    op.drop_table('quran_surahs')
    # ### end Alembic commands ###
